# Archivo: alacritty.toml.template
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.selection]
text = "#3c3836"
background = "#d79921"

[window] #1.0 es opaco, 0.0 es invisible.
opacity = 0.85
# Importnte: esto ayuda a que el fondo no distraiga tanto
blur = true

#Margen del texto
# [window.padding]
# x = 10
# y = 10
